export const Prizes = [
  "Colonic irrigation"
  ,  "Plastic lobster"
  ,  "A dog biscuit"
  ,  "Nit comb"
  ,  "Elaine Paige's used false eyelashes"
  ,  "Tartan Army songbook"
  ,  "Spider catcher"
  ,  "Ear cleaning kit"
  ,  "String of garlic"
  ,  "Can of Polo mint holes"
  ,  "Eight-course insect meal"
  ,  "Heart shaped bed"
  ,  "One teabag"
  ,  "Grow your own sprout kit"
  ,  "Remote control for curtains"
  ,  "Personalised baked bean"
  ,  "Pair of green lucky pants"
  ,  "Breeding to a premium graded stallion"
  ,  "Jar of fake snow"
  ,  "Your portrait drawn on a nut by Harry Hill"
  ,  "Six months supply of tampons"
  ,  "Feature as a character in a sex novel"
  ,  "Dragon's blood"
  ,  "Peanut tree"
  ,  "100 Chinese dinner sets"
  ,  "Spork"
  ,  "Empty tin to keep negative thoughts in"
  ,  "Book of knitting patterns for dog clothes"
  ,  "Car aerial ball"
  ,  "Chocolate teapot"
  ,  "Chicken manure"
  ,  "'Orgasmic Birth' DVD"
  ,  "Empty Jack Daniels barrel"
  ,  "Year's supply of salad cream"
  ,  "Vampire teeth in a coffin"
  ,  "Life size Justin Bieber cutout"
  ,  "Caravan cleaner"
  ,  "Bowling ball"
  ,  "Inflatable flea"
  ,  "Life sized baby dolphin toy"
  ,  "Disposable urinal"
  ,  "Live turkey"
  ,  "Bogey picking device"
  ,  "Tanking Slurry"
  ,  "Groin cleanser"
  ,  "Inflatable referee"
  ,  "Louisiana Lounger sex toy"
  ,  "Camel ride (at the local shopping centre)"
  ,  "Photo of someone eating a yoghurt"
  ]